default:
    resource: '../src/Controller/'
    type: annotation

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_account_edit:
    path: /account/edit
    controller: App\Controller\UserController::edit
